version: '3.7'

services:
  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    networks:
      - rabbitnet

  rabbitmq1:
    image: rabbitmq:3.8-management
    hostname: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=secretcookie
      - RABBITMQ_DEFAULT_USER=RV4r6hyu
      - RABBITMQ_DEFAULT_PASS=0Q#t[W:Cv:MW
    volumes:
      - rabbitmq1_data:/var/lib/rabbitmq
    networks:
      - rabbitnet

  rabbitmq2:
    image: rabbitmq:3.8-management
    hostname: rabbitmq2
    environment:
      - RABBITMQ_ERLANG_COOKIE=secretcookie
      - RABBITMQ_DEFAULT_USER=RV4r6hyu
      - RABBITMQ_DEFAULT_PASS=0Q#t[W:Cv:MW
    volumes:
      - rabbitmq2_data:/var/lib/rabbitmq
    networks:
      - rabbitnet

  rabbitmq3:
    image: rabbitmq:3.8-management
    hostname: rabbitmq3
    environment:
      - RABBITMQ_ERLANG_COOKIE=secretcookie
      - RABBITMQ_DEFAULT_USER=RV4r6hyu
      - RABBITMQ_DEFAULT_PASS=0Q#t[W:Cv:MW
    volumes:
      - rabbitmq3_data:/var/lib/rabbitmq
    networks:
      - rabbitnet

networks:
  rabbitnet:
    driver: bridge

volumes:
  rabbitmq1_data:
  rabbitmq2_data:
  rabbitmq3_data:
